Repository pagopa/pagopa-fdr-nodo-dei-pagamenti, pull requests merged in 2024-05, with the labels that each got.

#37 Nod 818 fdr anomalia recupero flussi nexi
  .run/MainTest dev.run.xml
  .run/MainTest local.run.xml
  build.sbt
  fdr/src/main/scala/eu/sia/pagopa/TestDData.scala
  fdr/src/main/scala/eu/sia/pagopa/TestUtil.scala
  fdr/src/main/scala/eu/sia/pagopa/common/json/model/rendicontazione/FdRHistoryPaymentsRevision.scala
  fdr/src/main/scala/eu/sia/pagopa/common/util/azurehubevent/Appfunction.scala
  fdr/src/main/scala/eu/sia/pagopa/rendicontazioni/actor/rest/NotifyFlussoRendicontazioneActor.scala
  fdr/src/main/scala/eu/sia/pagopa/rendicontazioni/actor/soap/NodoChiediElencoFlussiRendicontazioneActor.scala
  fdr/src/main/scala/eu/sia/pagopa/rendicontazioni/actor/soap/NodoChiediFlussoRendicontazioneActor.scala
  fdr/src/test/resources/mocks/internalGetFdrPayment/OK.json
  fdr/src/test/scala/eu/sia/pagopa/ChecksUnitTests.scala
  fdr/src/test/scala/eu/sia/pagopa/ConfigUnitTests.scala
  fdr/src/test/scala/eu/sia/pagopa/FormatUnitTests.scala
  fdr/src/test/scala/eu/sia/pagopa/MockserverExtension.scala
  helm/config/dev/config-app.conf
  helm/config/prod/config-app.conf
  helm/config/uat/config-app.conf
  helm/fdr-cron/Chart.yaml
  helm/fdr/Chart.yaml
  helm/fdr/neu-dev/values-dev.yaml
  helm/fdr/weu-dev/values-dev.yaml
  helm/fdr/weu-prod/values-prod.yaml
  helm/fdr/weu-uat/values-uat.yaml
  localresources/config-app.conf
  openapi/openapi.json
  version.sbt
Labels: bug, enhancement

#18 [NOD-508] Integration Test
  .github/auto_assign.yml
  .github/release.yml
  .github/workflows/00_anchore.yml
  .github/workflows/01_add_patch_label.yml
  .github/workflows/01_assignee.yml
  .github/workflows/02_check_pr.yml
  .github/workflows/03_code_review.yml
  .github/workflows/04_release_deploy.yml
  .github/workflows/04h_deploy_with_github_runner.yml
  .github/workflows/05_update_code.yml
  .github/workflows/06_integration_test.yml
  .gitignore
  .identity/.terraform.lock.hcl
  .identity/00_data.tf
  .identity/03_github_environment.tf
  .identity/99_main.tf
  .identity/99_variables.tf
  .identity/env/dev/backend.ini
  .identity/env/dev/backend.tfvars
  .identity/env/dev/terraform.tfvars
  .identity/env/prod/backend.ini
  .identity/env/prod/backend.tfvars
  .identity/env/prod/terraform.tfvars
  .identity/env/uat/backend.ini
  .identity/env/uat/backend.tfvars
  .identity/env/uat/terraform.tfvars
  .identity/terraform.sh
  index.html
  integration-test/Dockerfile
  integration-test/behave.ini
  integration-test/config/dev.json
  integration-test/config/uat.json
  integration-test/environment.py
  integration-test/features/RendicontazioneFTPeBollo/NIFRFTP_01.feature
  integration-test/features/RendicontazioneFTPeBollo/NIFRFTP_02.feature
  integration-test/features/RendicontazioneFTPeBollo/NIFRFTP_03.feature
  integration-test/features/RendicontazioneFTPeBollo/NIFRFTP_04.feature
  integration-test/features/RendicontazioneFTPeBollo/RMDB_FTP_01.feature
  integration-test/features/complete_flow.feature
  integration-test/features/nodoChiediElencoFlussiRendicontazione.feature
  integration-test/features/nodoChiediFlussoRendicontazione.feature
  integration-test/features/nodoInviaFlussoRendicontazione.feature
  integration-test/requirements.txt
  integration-test/run_test.sh
  integration-test/steps/steps.py
  integration-test/steps/utils.py
Labels: size/large, ignore-for-release

#38 feat: NOD-867: [FDR] Aggiunta codice esito pagamento 8
  common-xml/src/main/2.0/xsd/FlussoRiversamento_1_0_4.xsd
  fdr/src/main/scala/eu/sia/pagopa/common/json/model/rendicontazione/FdRHistoryPaymentsRevision.scala
  fdr/src/main/scala/eu/sia/pagopa/rendicontazioni/actor/rest/NotifyFlussoRendicontazioneActor.scala
Labels: enhancement

#39 [NOD-714] feat: integration test refactoring
  .github/workflows/06_integration_test.yml
  .identity/00_data.tf
  .identity/03_github_environment.tf
  integration-test/Dockerfile
  integration-test/features/nodoChiediElencoFlussiRendicontazione.feature
  integration-test/features/nodoChiediFlussoRendicontazione.feature
  integration-test/reports/app.js
  integration-test/reports/data/behaviors.csv
  integration-test/reports/data/behaviors.json
  integration-test/reports/data/categories.csv
  integration-test/reports/data/categories.json
  integration-test/reports/data/packages.json
  integration-test/reports/data/suites.csv
  integration-test/reports/data/suites.json
  integration-test/reports/data/timeline.json
  integration-test/reports/export/influxDbData.txt
  integration-test/reports/export/mail.html
  integration-test/reports/export/prometheusData.txt
  integration-test/reports/favicon.ico
  integration-test/reports/history/categories-trend.json
  integration-test/reports/history/duration-trend.json
  integration-test/reports/history/history-trend.json
  integration-test/reports/history/history.json
  integration-test/reports/history/retry-trend.json
  integration-test/reports/index.html
  integration-test/reports/plugins/behaviors/index.js
  integration-test/reports/plugins/packages/index.js
  integration-test/reports/plugins/screen-diff/index.js
  integration-test/reports/plugins/screen-diff/styles.css
  integration-test/reports/styles.css
  integration-test/reports/widgets/behaviors.json
  integration-test/reports/widgets/categories-trend.json
  integration-test/reports/widgets/categories.json
  integration-test/reports/widgets/duration-trend.json
  integration-test/reports/widgets/duration.json
  integration-test/reports/widgets/environment.json
  integration-test/reports/widgets/executors.json
  integration-test/reports/widgets/history-trend.json
  integration-test/reports/widgets/launch.json
  integration-test/reports/widgets/retry-trend.json
  integration-test/reports/widgets/severity.json
  integration-test/reports/widgets/status-chart.json
  integration-test/reports/widgets/suites.json
  integration-test/reports/widgets/summary.json
  integration-test/requirements.txt
  integration-test/run_test.sh
  integration-test/steps/steps.py
Labels: size/large, ignore-for-release

#40 [NOD-576] feat: add performance test pipeline
  .github/workflows/07_performance_test.yml
  fdr/src/main/resources/openapi_config.json
  fdr/src/main/scala/eu/sia/pagopa/TestDData.scala
  fdr/src/test/scala/eu/sia/pagopa/testutil/TestDData.scala
  helm/fdr-cron/Chart.yaml
  helm/fdr/Chart.yaml
  integration-test/config/dev.json
  integration-test/config/uat.json
  openapi/openapi.json
  performance-test/README.md
  performance-test/docker-compose.yaml
  performance-test/nginx/nginx_dev.conf
  performance-test/nginx/nginx_uat.conf
  performance-test/run_performance_test.sh
  performance-test/src/README.md
  performance-test/src/environments/dev.environment.json
  performance-test/src/environments/local.environment.json
  performance-test/src/environments/uat.environment.json
  performance-test/src/happy_case_scenario.js
  performance-test/src/helpers/fdr_helpers.js
  performance-test/src/modules/client.js
  performance-test/src/only_nodoInviaFlussoRendicontazione_scenario.js
  performance-test/src/test-types/constant.json
  performance-test/src/test-types/load.json
  performance-test/src/test-types/ramping.json
  performance-test/src/test-types/smoke.json
  performance-test/src/test-types/soak.json
  performance-test/src/test-types/spike.json
  performance-test/src/test-types/stress.json
  version.sbt
Labels: size/large, ignore-for-release
