Repository pagopa/pagopa-fdr-nodo-dei-pagamenti, pull requests merged in 2025-03, with the labels that each got.

#91 [PAGOPA-2268] ci(helm): Update liveness config
  helm-fdr/helm/values-prod.yaml
Labels: patch, size/small, skip

#95 chore: Add `fdr1r` user read 4 SMO
  .devops/fdr-db-schema-pipelines.yml
Labels: ignore-for-release, size/small

#94 [PIDM-330] fix: Integration test FDR
  .github/workflows/07_performance_test.yml
  integration-test/config/uat.json
  integration-test/run_test.sh
  performance-test/src/environments/dev.environment.json
  performance-test/src/environments/local.environment.json
  performance-test/src/environments/uat.environment.json
  performance-test/src/happy_case_scenario.js
Labels: patch, size/small

#96 [PAGOPA-2753] feat: Add new Convert API
  .gitignore
  fdr/src/main/resources/json-schemas/convert.json
  fdr/src/main/resources/json-schemas/convertFlowRendicontazione.json
  fdr/src/main/resources/json-schemas/notifyFlowRendicontazione.json
  fdr/src/main/scala/eu/sia/pagopa/common/json/JsonEnum.scala
  fdr/src/main/scala/eu/sia/pagopa/common/json/JsonValid.scala
  fdr/src/main/scala/eu/sia/pagopa/common/json/model/rendicontazione/Convert.scala
  fdr/src/main/scala/eu/sia/pagopa/common/json/model/rendicontazione/Flow.scala
  fdr/src/main/scala/eu/sia/pagopa/common/json/model/rendicontazione/FlowPayment.scala
  fdr/src/main/scala/eu/sia/pagopa/common/json/model/rendicontazione/NotifyFdr.scala
  fdr/src/main/scala/eu/sia/pagopa/common/json/model/rendicontazione/Receiver.scala
  fdr/src/main/scala/eu/sia/pagopa/common/json/model/rendicontazione/Sender.scala
  fdr/src/main/scala/eu/sia/pagopa/common/util/Appfunction.scala
  fdr/src/main/scala/eu/sia/pagopa/common/util/Primitive.scala
  fdr/src/main/scala/eu/sia/pagopa/common/util/web/NodoRoute.scala
  fdr/src/main/scala/eu/sia/pagopa/rendicontazioni/actor/rest/ConvertFlussoRendicontazioneActorPerRequest.scala
  fdr/src/test/resources/requests/convertFlow.json
  fdr/src/test/scala/eu/sia/pagopa/ActorErrorUnitTests.scala
  fdr/src/test/scala/eu/sia/pagopa/BaseUnitTest.scala
  fdr/src/test/scala/eu/sia/pagopa/RestRendicontazioniTests.scala
  fdr/src/test/scala/eu/sia/pagopa/testutil/TestUtil.scala
  helm-fdr/helm/Chart.yaml
  helm-fdr/helm/values-dev.yaml
  helm-fdr/helm/values-prod.yaml
  helm-fdr/helm/values-uat.yaml
  openapi/openapi.json
  version.sbt
Labels: size/large, patch

#97 feat: [PAGOPA-2473] Implement workload identity & new runner
  .github/workflows/04_release_deploy.yml
  .github/workflows/04h_deploy_with_github_runner.yml
  .identity/.terraform.lock.hcl
  .identity/00_data.tf
  .identity/03_github_environment.tf
  .identity/99_main.tf
  helm-cron/helm/README.md
  helm-cron/helm/values-dev.yaml
  helm-cron/helm/values-prod.yaml
  helm-cron/helm/values-uat.yaml
  helm-fdr/helm/Chart.yaml
  helm-fdr/helm/values-dev.yaml
  helm-fdr/helm/values-prod.yaml
  helm-fdr/helm/values-uat.yaml
  helm-prf/helm/Chart.yaml
  helm-prf/helm/config/uat/config-app.conf
  helm-prf/helm/config/uat/logback.xml
  helm-prf/helm/values-uat.yaml
Labels: size/large, skip

#98 fix(helm-fdr): update ingress path for production, UAT, and dev environments
  fdr/src/test/scala/eu/sia/pagopa/BaseUnitTest.scala
  helm-cron/helm/values-dev.yaml
  helm-cron/helm/values-prod.yaml
  helm-cron/helm/values-uat.yaml
  helm-fdr/helm/Chart.yaml
  helm-fdr/helm/values-dev.yaml
  helm-fdr/helm/values-prod.yaml
  helm-fdr/helm/values-uat.yaml
  localresources/config-app.conf
  openapi/openapi.json
  version.sbt
Labels: patch, size/small
