Repository pagopa/pagopa-fdr-nodo-dei-pagamenti, pull requests merged in 2025-02, with the labels that each got.

#66 feat: [PAGOPA-2622] Code review on GHA
  .devops/code-review-pipelines.yml
  .devops/deploy-pipelines.yml
  .github/workflows/03_code_review.yml
  project/plugins.sbt
Labels: size/large, ignore-for-release, skip

#70 feat(gha): new scheduled action
  .github/workflows/gh_runner-scheduler.yml
  .identity/00_data.tf
  .identity/03_github_environment.tf
Labels: patch, size/small

#69 feat: [PAGOPA-2631] Add performance test for FDR org API
  .devops/performance-test-pipelines.yaml
  performance-test/src/environments/dev.environment.json
  performance-test/src/environments/local.environment.json
  performance-test/src/environments/uat.environment.json
  performance-test/src/nodoChiediElencoFlussiRendicontazione_scenario.js
  performance-test/src/nodoChiediFlussoRendicontazione_scenario.js
  performance-test/src/test-types/constant_nodoChiediElencoFlussi.json
  performance-test/src/test-types/constant_nodoChiediFlusso.json
  performance-test/src/test-types/spike_nodoChiediElencoFlussi.json
  performance-test/src/test-types/spike_nodoChiediFlusso.json
Labels: ignore-for-release, patch, skip

#74 chore: HotFix nodoChiediFlussoRendicontazione
  fdr/src/main/scala/eu/sia/pagopa/rendicontazioni/actor/soap/NodoChiediFlussoRendicontazioneActor.scala
  helm-fdr/helm/Chart.yaml
  helm-fdr/helm/values-dev.yaml
  helm-fdr/helm/values-prod.yaml
  helm-fdr/helm/values-uat.yaml
  openapi/openapi.json
  version.sbt
Labels: patch, size/small

#75 Fix input gh
  .devops/performance-test-pipelines.yaml
  .github/workflows/07_performance_test.yml
  performance-test/src/environments/uat.environment.json
  performance-test/src/nodoChiediElencoFlussiRendicontazione_scenario.js
  performance-test/src/nodoChiediFlussoRendicontazione_scenario.js
  performance-test/src/only_nodoInviaFlussoRendicontazione_payments_ramp_scenario.js
  performance-test/src/only_nodoInviaFlussoRendicontazione_scenario.js
  performance-test/src/only_nodoInviaFlussoRendicontazione_scenario_5k150k.js
  performance-test/src/only_nodoInviaFlussoRendicontazione_scenario_5k50k.js
  performance-test/src/test-types/constant.json
Labels: enhancement, ignore-for-release, size/small

#76 feat: [PAGOPA-2671] New endpoint for register flows for validation on `nodoInviaFlussoRendicontazione`
  .gitignore
  .run/MainTest local.run.xml
  .run/MainTestJob.run.xml
  README.md
  fdr/src/main/resources/draft-schemas/json-schema-draft-04.json
  fdr/src/main/resources/draft-schemas/json-schema-draft-07.json
  fdr/src/main/resources/json-schemas/registerFdrForValidation.json
  fdr/src/main/scala/eu/sia/pagopa/common/json/JsonEnum.scala
  fdr/src/main/scala/eu/sia/pagopa/common/json/JsonValid.scala
  fdr/src/main/scala/eu/sia/pagopa/common/json/model/rendicontazione/RegisterFdrForValidation.scala
  fdr/src/main/scala/eu/sia/pagopa/common/json/schema/drafts/Version4.scala
  fdr/src/main/scala/eu/sia/pagopa/common/json/schema/drafts/Version7.scala
  fdr/src/main/scala/eu/sia/pagopa/common/repo/fdr/FdrRepository.scala
  fdr/src/main/scala/eu/sia/pagopa/common/util/Appfunction.scala
  fdr/src/main/scala/eu/sia/pagopa/common/util/Primitive.scala
  fdr/src/main/scala/eu/sia/pagopa/common/util/web/NodoRoute.scala
  fdr/src/main/scala/eu/sia/pagopa/rendicontazioni/actor/BaseFlussiRendicontazioneActor.scala
  fdr/src/main/scala/eu/sia/pagopa/rendicontazioni/actor/rest/RegisterFdrForValidationActor.scala
  fdr/src/test/scala/eu/sia/pagopa/ActorErrorUnitTests.scala
  fdr/src/test/scala/eu/sia/pagopa/BaseUnitTest.scala
  fdr/src/test/scala/eu/sia/pagopa/PollerActorUnitTests.scala
  fdr/src/test/scala/eu/sia/pagopa/RestRendicontazioniTests.scala
  helm-fdr/helm/Chart.yaml
  helm-fdr/helm/values-dev.yaml
  helm-fdr/helm/values-prod.yaml
  helm-fdr/helm/values-uat.yaml
  openapi/openapi.json
  version.sbt
Labels: enhancement, size/large, patch

#78 chore: Fix JAVA_OPTS and scaling config
  helm-fdr/helm/values-prod.yaml
  helm-fdr/helm/values-uat.yaml
Labels: patch, size/small

#79 chore: Fix memory
  helm-fdr/helm/values-dev.yaml
  helm-fdr/helm/values-prod.yaml
  helm-fdr/helm/values-uat.yaml
Labels: patch, size/small

#81 Pagopa 2643 fdr 1 soak testing
  .devops/performance-test-pipelines.yaml
  performance-test/src/only_nodoInviaFlussoRendicontazione_scenario_soak.js
  performance-test/src/test-types/constantSoak.json
  performance-test/src/test-types/constant_nodoChiediElencoFlussi.json
  performance-test/src/test-types/constant_nodoChiediFlusso.json
Labels: enhancement, ignore-for-release, size/small

#80 feat: [PagoPA-2672] - fk binary file filter
  fdr/src/main/scala/eu/sia/pagopa/common/repo/fdr/FdrRepository.scala
  fdr/src/test/scala/eu/sia/pagopa/BaseUnitTest.scala
  fdr/src/test/scala/eu/sia/pagopa/RendicontazioniTests.scala
Labels: patch, size/small

#83 feat: Tuning deploy prod-cfg
  .gitignore
  helm-fdr/helm/values-prod.yaml
  helm-fdr/helm/values-uat.yaml
Labels: ignore-for-release, size/small

#84 PAGOPA-2680-fd-r-1-finalizzare-integration-test
  integration-test/config/dev.json
  integration-test/config/uat.json
  integration-test/environment.py
  integration-test/features/nodoInviaFlussoRendicontazione.feature
  integration-test/run_test.sh
Labels: patch, size/small

#77 chore: [PAGOPA-2669] Script to insert data in rendicontazione table
  utils/rendicontazione_insert.py
Labels: ignore-for-release, size/small

#82 feat: [PAGOPA-2682] defining health check API
  fdr/src/main/scala/eu/sia/pagopa/Main.scala
  fdr/src/main/scala/eu/sia/pagopa/common/util/web/NodoRoute.scala
  helm-fdr/helm/Chart.yaml
  helm-fdr/helm/values-dev.yaml
  helm-fdr/helm/values-prod.yaml
  helm-fdr/helm/values-uat.yaml
  openapi/openapi.json
  version.sbt
Labels: bug, patch, size/small

#86 chore: [PIDM-211] Reduced log severity
  fdr/src/main/scala/eu/sia/pagopa/common/actor/ActorUtility.scala
  fdr/src/main/scala/eu/sia/pagopa/common/util/web/NodoRoute.scala
  fdr/src/main/scala/eu/sia/pagopa/restinput/actor/RestActorPerRequest.scala
  fdr/src/main/scala/eu/sia/pagopa/soapinput/actor/SoapActorPerRequest.scala
Labels: patch, size/small

#87 feat: [PAGOPA-2687] Housekeeping on endpoint logs for better request tracing
  .gitignore
  fdr/src/main/scala/eu/sia/pagopa/common/actor/ActorUtility.scala
  fdr/src/main/scala/eu/sia/pagopa/common/actor/FuturePerRequestActor.scala
  fdr/src/main/scala/eu/sia/pagopa/common/actor/PerRequestActor.scala
  fdr/src/main/scala/eu/sia/pagopa/common/util/ConfigUtil.scala
  fdr/src/main/scala/eu/sia/pagopa/common/util/FdrLogConstant.scala
  fdr/src/main/scala/eu/sia/pagopa/common/util/web/NodoRoute.scala
  fdr/src/main/scala/eu/sia/pagopa/config/actor/ApiConfigActor.scala
  fdr/src/main/scala/eu/sia/pagopa/config/actor/FdRMetadataActor.scala
  fdr/src/main/scala/eu/sia/pagopa/ftpsender/actor/FtpRetryActor.scala
  fdr/src/main/scala/eu/sia/pagopa/ftpsender/actor/FtpSenderActor.scala
  fdr/src/main/scala/eu/sia/pagopa/nodopoller/actor/PollerActor.scala
  fdr/src/main/scala/eu/sia/pagopa/rendicontazioni/actor/BaseFlussiRendicontazioneActor.scala
  fdr/src/main/scala/eu/sia/pagopa/rendicontazioni/actor/rest/GetAllRevisionFdrActor.scala
  fdr/src/main/scala/eu/sia/pagopa/rendicontazioni/actor/rest/NodoInviaFlussoRendicontazioneFTPActor.scala
  fdr/src/main/scala/eu/sia/pagopa/rendicontazioni/actor/rest/NotifyFlussoRendicontazioneActor.scala
  fdr/src/main/scala/eu/sia/pagopa/rendicontazioni/actor/rest/RegisterFdrForValidationActor.scala
  fdr/src/main/scala/eu/sia/pagopa/rendicontazioni/actor/soap/NodoChiediElencoFlussiRendicontazioneActor.scala
  fdr/src/main/scala/eu/sia/pagopa/rendicontazioni/actor/soap/NodoChiediFlussoRendicontazioneActor.scala
  fdr/src/main/scala/eu/sia/pagopa/rendicontazioni/actor/soap/NodoInviaFlussoRendicontazioneActor.scala
  fdr/src/main/scala/eu/sia/pagopa/restinput/actor/RestActorPerRequest.scala
  fdr/src/main/scala/eu/sia/pagopa/soapinput/actor/SoapActorPerRequest.scala
  helm-fdr/helm/Chart.yaml
  helm-fdr/helm/config/prod/logback.xml
  helm-fdr/helm/values-dev.yaml
  helm-fdr/helm/values-prod.yaml
  helm-fdr/helm/values-uat.yaml
  openapi/openapi.json
  version.sbt
Labels: bug, patch, size/small

#88 fix: reducing logs for some primitives
  fdr/src/main/scala/eu/sia/pagopa/common/util/web/NodoRoute.scala
  fdr/src/main/scala/eu/sia/pagopa/rendicontazioni/actor/rest/NodoInviaFlussoRendicontazioneFTPActor.scala
  helm-fdr/helm/config/prod/logback.xml
  helm-fdr/helm/config/uat/logback.xml
Labels: bug, patch, size/small

#89 [PAGOPA-2702] feat(liquidbase): Replace indexes
  infra/psql/liquibase/changelog/1.0.2/db.changelog-20250227000000_fix-varchar.xml
  infra/psql/liquibase/changelog/db.changelog-master-1.0.2.xml
Labels: patch, size/small
