Repository pagopa/pagopa-fdr-nodo-dei-pagamenti, pull requests merged in 2025-04, with the labels that each got.

#102 fix: uat integration test configuration
  integration-test/config/uat.json
  integration-test/features/complete_flow.feature
  integration-test/steps/steps.py
Labels: size/small, skip

#104 fix: [PAGOPA-2716] changed POST_URL endpoint
  utils/base64.js
  utils/chunked.sh
  utils/nodoInviaFlussoRendicontazione.sh
Labels: size/small, skip

#105 fix: [PAGOPA-2978] Resolving payment amounts types in decimal values
  fdr/src/main/resources/json-schemas/convertFlowRendicontazione.json
  fdr/src/main/scala/eu/sia/pagopa/common/json/model/rendicontazione/Flow.scala
  fdr/src/main/scala/eu/sia/pagopa/common/json/model/rendicontazione/FlowPayment.scala
  fdr/src/main/scala/eu/sia/pagopa/rendicontazioni/actor/rest/ConvertFlussoRendicontazioneActorPerRequest.scala
  helm-fdr/helm/Chart.yaml
  helm-fdr/helm/values-dev.yaml
  helm-fdr/helm/values-prod.yaml
  helm-fdr/helm/values-uat.yaml
  openapi/openapi.json
  version.sbt
Labels: patch, size/small

#101 chore: [PAGOPA-2872] Configuration housekeeping
  helm-fdr/helm/config/dev/config-app.conf
  helm-fdr/helm/config/prod/config-app.conf
  helm-fdr/helm/config/uat/config-app.conf
  helm-fdr/helm/values-dev.yaml
  helm-fdr/helm/values-prod.yaml
  helm-fdr/helm/values-uat.yaml
  localresources/config-app.conf
Labels: size/small, skip

#106 fix: restored PAGOPA-2720
  helm-fdr/helm/config/dev/config-app.conf
  helm-fdr/helm/config/prod/config-app.conf
  helm-fdr/helm/config/uat/config-app.conf
  helm-fdr/helm/values-dev.yaml
  helm-fdr/helm/values-prod.yaml
  helm-fdr/helm/values-uat.yaml
Labels: patch, size/small

#107 fix: [PAGOPA-2696] Including `PartitionKey` fields in MongoDB documents
  fdr/src/main/scala/eu/sia/pagopa/common/message/ReMessage.scala
  fdr/src/main/scala/eu/sia/pagopa/common/repo/re/model/Fdr1Metadata.scala
  helm-fdr/helm/Chart.yaml
  helm-fdr/helm/values-dev.yaml
  helm-fdr/helm/values-prod.yaml
  helm-fdr/helm/values-uat.yaml
  openapi/openapi.json
  version.sbt
Labels: bug, patch, size/small
